### ISSUE TITLE
How does this differ from ipfs-fuse?

### ISSUE THREAD

**Issue by hacdias** [piedar/js-ipfs-mount#10]
Looking at the overall functionality through the README, I was wondering how this differs from ipfs-fuse. Could you explain me?

**Comment by piedar** [comment]
This project uses [ipfs-fuse](https://github.com/tableflip/ipfs-fuse) underneath for some of the MFS functionality.  ipfs-fuse itself only supports /mfs (not /ipfs or /ipns) and its command-line interface is not quite what I wanted.
